services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV
      - CERTIFICATES_PATH
    volumes:
      - ./nginx/${ENV}/:/etc/nginx
      - ${CERTIFICATES_PATH}/:/etc/nginx/certificates
    networks:
      - nginx
      - minio

  watchtower:
    image: containrrr/watchtower
    command: 
    - "--label-enable"
    - "--interval"
    - "30"
    - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # home:
  #   image: bpasco/production:home
  #   platform: linux/amd64
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   environment:
  #     - HOST=true
  #     - NODE_ENV=production
  #     - PORT=8000
  #   # deploy:
  #   #   mode: replicated
  #   #   replicas: 2
  #   restart: unless-stopped
  #   networks:
  #     - nginx

  spotify:
    image: bpasco/spotify:latest
    platform: linux/amd64
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NODE_ENV=production
      - PORT=${SPOTIFY_PORT}
      - DOMAIN=${SPOTIFY_DOMAIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    # deploy:
    #   mode: replicated
    #   replicas: 2
    restart: unless-stopped
    networks:
      - nginx
      - minio
      - db

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"  # to be removed
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"  # to be removed
    command: server /data --console-address ":${MINIO_GUI_PORT}"
    ports:
      - "${MINIO_EXPOSED_PORT}:${MINIO_PORT}"
      - "${MINIO_GUI_EXPOSED_PORT}:${MINIO_GUI_PORT}"
    volumes:
      - minio:/data
    networks:
      - minio

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSED_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - db

networks:
  nginx:
    driver: bridge 
  minio:
    driver: bridge
  db:
    driver: bridge

volumes:
  minio:
  postgres_data:
  letsencrypt: