services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV
      - CERTIFICATES_PATH
    volumes:
      - ./nginx/${ENV}/:/etc/nginx
      - ${CERTIFICATES_PATH}/:/etc/nginx/certificates
    networks:
      - nginx
      - minio

  spotify:
    image: bpasco/spotify:latest
    platform: linux/amd64
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - DOMAIN=${SPOTIFY_DOMAIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
    restart: unless-stopped
    networks:
      - nginx
      - minio
      - db

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - minio

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - db

networks:
  nginx:
    driver: bridge
  minio:
    driver: bridge
  db:
    driver: bridge

volumes:
  minio:
  postgres_data:
  letsencrypt:
