services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV
      - CERTIFICATES_PATH
    volumes:
      - ./nginx/${ENV}/:/etc/nginx
      - ${CERTIFICATES_PATH}/:/etc/nginx/certificates
    networks:
      - nginx
      - minio

  spotify:
    image: bpasco/spotify:latest
    platform: linux/amd64
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NODE_ENV=production
      - PORT=${SPOTIFY_PORT}
      - DOMAIN=${SPOTIFY_DOMAIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    restart: unless-stopped
    networks:
      - nginx
      - minio
      - db

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"
    command: server /data --console-address ":${MINIO_GUI_PORT}"
    ports:
      - "${MINIO_EXPOSED_PORT}:${MINIO_PORT}"
      - "${MINIO_GUI_EXPOSED_PORT}:${MINIO_GUI_PORT}"
    volumes:
      - minio:/data
    networks:
      - minio

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSED_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - db

  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
      - ./vault/config/vault.hcl:/vault/config/vault.hcl
    command: "server -config=/vault/config/vault.hcl"

networks:
  nginx:
    driver: bridge 
  minio:
    driver: bridge
  db:
    driver: bridge

volumes:
  minio:
  postgres_data:
  letsencrypt:
  vault_data:
